pipeline {
    agent any

    environment {
        IMAGE_NAME = "ml-inference-api"
        SONAR_TOKEN = credentials('sonar')
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'Git',
                    url: 'https://github.com/Karthikbale/ml-inference-api.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonar') {
                    script {
                        def scannerHome = tool 'SonarScanner'
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=ml-project \
                            -Dsonar.sources=. \
                            -Dsonar.host.url=http://sonarqube:9000
                        """
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME} .
                """
            }
        }

        stage('Deploy Container') {
            steps {
                sh """
                    docker rm -f ml-container || true
                    docker run -d -p 8000:8000 --name ml-container ${IMAGE_NAME}
                """
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully 🚀"
        }
        failure {
            echo "Pipeline failed ❌"
        }
    }
}
