pipeline {
    agent any

    environment {
        IMAGE_NAME = "ml-inference-api"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/Karthikbale/ml-inference-api.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('ml-inference-api') {
                    withSonarQubeEnv('Sonar') {
                        sh '''
                        sonar-scanner \
                        -Dsonar.projectKey=ml-project \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=http://sonarqube:9000 \
                        -Dsonar.login=$SONAR_TOKEN
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ml-inference-api') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker stop ml-container || true
                docker rm ml-container || true
                docker run -d -p 8000:8000 --name ml-container $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline successful 🚀'
        }
        failure {
            echo 'Pipeline failed ❌'
        }
    }
}
